/* Bundle spoken audio for every character.

   Why bundle rather than use the browser's speech engine: speechSynthesis is
   blocked in the cross-origin frame artifacts are embedded in, and several
   voices macOS lists have no voice data and produce silence. Bundled clips
   play through a plain <audio> element, which works there.

   Needs macOS `say` and `afconvert`.  Run: node tools/make-audio.mjs */

import { execFileSync } from 'child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { join } from 'path';
import { tmpdir } from 'os';

const VOICE = process.argv[2] || 'Tingting';
const BITRATE = '24000';
const MIN_SECONDS = 0.15;          /* shorter than this means the voice is mute */

const root = fileURLToPath(new URL('../', import.meta.url));
const { HQ } = new Function(readFileSync(join(root, 'js/data.js'), 'utf8') + '\nreturn {HQ};')();
const work = mkdtempSync(join(tmpdir(), 'hq-audio-'));

const clips = {};
const silent = [];
let bytes = 0;

process.stdout.write(`speaking ${HQ.length} characters as ${VOICE}\n`);
HQ.forEach((ch, i) => {
  const aiff = join(work, 'c.aiff'), m4a = join(work, 'c.m4a');
  execFileSync('say', ['-v', VOICE, '-o', aiff, ch.c]);
  const info = execFileSync('afinfo', [aiff]).toString();
  const dur = parseFloat((info.match(/estimated duration: ([\d.]+)/) || [])[1] || '0');
  if (dur < MIN_SECONDS) { silent.push(ch.c); return; }
  execFileSync('afconvert', ['-f', 'm4af', '-d', 'aac', '-b', BITRATE, aiff, m4a]);
  clips[ch.c] = readFileSync(m4a).toString('base64');
  bytes += statSync(m4a).size;
  if ((i + 1) % 40 === 0) process.stdout.write(`  ${i + 1}/${HQ.length}\n`);
});
rmSync(work, { recursive: true, force: true });

const out = `/* Spoken audio, generated by tools/make-audio.mjs (voice: ${VOICE}).
   The browser's speech engine is unavailable inside an embedded frame, so the
   clips ship with the page. Regenerate after adding characters. */
window.HQ_AUDIO = ${JSON.stringify(clips)};
`;
writeFileSync(join(root, 'js/audio.js'), out);

console.log(`\nbundled ${Object.keys(clips).length} clips`);
if (silent.length) console.log(`no audio for: ${silent.join(' ')}`);
console.log(`audio ${(bytes / 1024 / 1024).toFixed(2)} MB → js/audio.js ${(out.length / 1024 / 1024).toFixed(2)} MB`);
